// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM7gR4p6M11s5ND8ZrxyGhD2_vuK1DBZE',
    appId: '1:698687219921:web:398356fa39a848eab83df0',
    messagingSenderId: '698687219921',
    projectId: 'test-7a538',
    authDomain: 'test-7a538.firebaseapp.com',
    storageBucket: 'test-7a538.firebasestorage.app',
    measurementId: 'G-M97CMP8KEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRvLm_3eySn6eiXhqDPn5MRX0kuJNCsgk',
    appId: '1:698687219921:android:dc3f5029a7fd620cb83df0',
    messagingSenderId: '698687219921',
    projectId: 'test-7a538',
    storageBucket: 'test-7a538.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-KSoDE_UXZBlRj94E3XhR449oqO7EsKU',
    appId: '1:698687219921:ios:d957c2ef9052b6cbb83df0',
    messagingSenderId: '698687219921',
    projectId: 'test-7a538',
    storageBucket: 'test-7a538.firebasestorage.app',
    iosClientId: '698687219921-os3ta4vaulreq4eoc10ghgphi00h0kdm.apps.googleusercontent.com',
    iosBundleId: 'com.example.testAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-KSoDE_UXZBlRj94E3XhR449oqO7EsKU',
    appId: '1:698687219921:ios:d957c2ef9052b6cbb83df0',
    messagingSenderId: '698687219921',
    projectId: 'test-7a538',
    storageBucket: 'test-7a538.firebasestorage.app',
    iosClientId: '698687219921-os3ta4vaulreq4eoc10ghgphi00h0kdm.apps.googleusercontent.com',
    iosBundleId: 'com.example.testAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM7gR4p6M11s5ND8ZrxyGhD2_vuK1DBZE',
    appId: '1:698687219921:web:65dd1cc7c1bd8757b83df0',
    messagingSenderId: '698687219921',
    projectId: 'test-7a538',
    authDomain: 'test-7a538.firebaseapp.com',
    storageBucket: 'test-7a538.firebasestorage.app',
    measurementId: 'G-KRV9LBGBTL',
  );
}
